smartlabs:
  serialport:
    name: COM3
    #name: ttyAMA0
    baudrate: 57600
  gateway:
    address: 9130346C
    protocol: 
      prefix: efef00
      adress: 1234
      suffix: ff
  server:
    startup: 9999
    shutdown: 9991
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/230518-lab?serverTimezone=GMT%2B8&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: briup
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
  redis:
    host: 127.0.0.1
    port: 6379
    
    
    
    
    
    